
<img src=""
     style="display:block;margin:auto;width:10%"/>
<br>

<div style="text-align:center; font-size:200%;">
 <b>Erzeugen von Pandas Data Frames</b>
</div>
<br/>
<div style="text-align:center;">Dr. Matthias Hölzl</div>
<br/>
<!-- 02 Erzeugen von Pandas Data Frames.ipynb -->
<!-- python_courses/slides/module_610_pandas/topic_120_pandas_data_frames_1.py -->

In [1]:
from pathlib import Path
import numpy as np
import pandas as pd
import os

In [2]:
PANDAS_DIR_FROM_ENV = os.getenv("PANDAS_DIR_PATH")
if PANDAS_DIR_FROM_ENV:
    pandas_dir_path = Path(PANDAS_DIR_FROM_ENV)
else:
    pandas_dir_path = Path("data/pandas").absolute()
print(f"Pandas data: {pandas_dir_path}")

Pandas data: C:\Users\Cedri\repos\ml-grundkurs\ml-grundkurs 2\Notebooks\CodeAlong\Pandas\data\pandas

In [3]:
csv_file = pandas_dir_path / "example_data.csv"
excel_file1 = pandas_dir_path / "excel_data.xlsx"
excel_file2 = pandas_dir_path / "excel_other_sheet.xlsx"

In [5]:
os.listdir(pandas_dir_path)

['01 Pandas Data Frames Basics.ipynb',
 'california-housing.csv',
 'colors.png',
 'colors.xcf',
 'example_data.csv',
 'excel_data.xlsx',
 'excel_other_sheet.xlsx',
 'simple_df.csv',
 'tabby-cat-64.png',
 'wines.csv']

## Erzeugen von Data Frames

### Aus einer Liste oder einem NumPy Array

In [6]:
df = pd.DataFrame([[1, 2], [3, 4], [5, 6], [7, 8]], columns=["A", "B"])

In [7]:
df

   A  B
0  1  2
1  3  4
2  5  6
3  7  8

In [8]:
def create_data_frame():
    rng = np.random.default_rng(42)
    array = rng.normal(size=(5, 4), loc=5.0, scale=2.0)
    index = ["A", "B", "C", "D", "E"]
    columns = ["w", "x", "y", "z"]
    return pd.DataFrame(array, index=index, columns=columns)

In [9]:
df = create_data_frame()
df

          w         x         y         z
A  5.609434  2.920032  6.500902  6.881129
B  1.097930  2.395641  5.255681  4.367515
C  4.966398  3.293912  6.758796  6.555584
D  5.132061  7.254482  5.935019  3.281415
E  5.737502  3.082235  6.756901  4.900148

### Aus einer CSV Datei

In [10]:
df_csv = pd.read_csv(csv_file)
df_csv

,Unnamed: 0,Col 0,Col 1,Col 2,Col 3,Col 4,Col 5,Col 6,Col 7
0,Index 0,4.076693,-11.592472,5.758058,1.995488,7.433482,-2.697633,10.386505,1.392989
1,Index 1,-8.091764,-9.263259,13.398781,3.364558,-4.504057,13.487790,19.387826,10.307054
2,Index 2,-9.967062,17.347022,-7.131536,8.946958,-4.560652,-1.350351,10.932789,14.030532
3,Index 3,4.473407,-4.188944,-9.067113,-20.351787,10.067044,-11.084616,-2.390302,-10.064766
4,Index 4,-10.909624,3.213494,18.101500,10.736058,-6.578314,4.997114,-6.464901,0.021843
...,...,...,...,...,...,...,...,...,...
995,Index 995,-14.445522,6.513853,-6.446964,-10.729593,-2.300384,14.966634,-4.796942,-12.922157
996,Index 996,12.300935,1.203874,5.127201,-13.744109,1.032070,14.428249,-12.334804,12.607952
997,Index 997,3.074044,6.492773,-2.589086,-11.088337,1.747953,16.040783,3.921457,-4.266764
998,Index 998,4.563576,14.066358,-4.915146,-6.283678,-1.343589,-22.898390,-6.044495,-14.400880
999,Index 999,8.426685,16.927540,12.667732,26.127088,8.269967,8.847097,-1.603626,17.094113

In [16]:
!conda install --yes -c anaconda openpyxl

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Cedri\anaconda3\envs\ml-basic

  added / updated specs:
    - openpyxl


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    et_xmlfile-1.0.1           |          py_1001          11 KB  anaconda
    openpyxl-3.0.9             |     pyhd3eb1b0_0         159 KB  anaconda
    ------------------------------------------------------------
                                           Total:         170 KB

The following NEW packages will be INSTALLED:

  et_xmlfile         anaconda/noarch::et_xmlfile-1.0.1-py_1001
  openpyxl           anaconda/noarch::openpyxl-3.0.9-pyhd3eb1b0_0



Downloading and Extracting Packages

openpyxl-3.0.9       | 159 KB    |            |   0%

et_xmlfile-1.0.1     | 11 KB     |            |   0%
openpyxl-3.0.9       | 159 KB    | #          |  10%

et_xmlfile-1.0.1     | 11 KB     | ########## | 100%

et_xmlfile-1.0.1     | 11 KB     | ########## | 100%
openpyxl-3.0.9       | 159 KB    | ########## | 100%
openpyxl-3.0.9       | 159 KB    | ########## | 100%





Preparing transaction: ...working... done
Executing transaction: ...working... done

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/win-64/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/win-64/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/noarch/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/noarch/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/msys2/noarch/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/msys2/win-64/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /anaconda/noarch/openpyxl-3.0.9-pyhd3eb1b0_0.tar.bz2 HTTP/1.1" 200 163044
DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /anaconda/noarch/et_xmlfile-1.0.1-py_1001.tar.bz2 HTTP/1.1" 200 11239

In [17]:
df_excel = pd.read_excel(excel_file1)

In [18]:
df_excel

,Unnamed: 0,Col 0,Col 1,Col 2,Col 3,Col 4,Col 5,Col 6,Col 7,Col 8,Col 9,Col 10,Col 11
0,Index 0,4.076693,-11.592472,5.758058,1.995488,7.433482,-2.697633,10.386505,1.392989,-8.091764,-9.263259,13.398781,3.364558
1,Index 1,-4.504057,13.487790,19.387826,10.307054,-9.967062,17.347022,-7.131536,8.946958,-4.560652,-1.350351,10.932789,14.030532
2,Index 2,4.473407,-4.188944,-9.067113,-20.351787,10.067044,-11.084616,-2.390302,-10.064766,-10.909624,3.213494,18.101500,10.736058
3,Index 3,-6.578314,4.997114,-6.464901,0.021843,-2.473564,-19.782094,11.556567,4.545686,13.854239,-1.138480,-1.245364,-24.905710
4,Index 4,-0.753812,-3.029928,-10.729667,-12.453821,-13.675471,6.621271,-10.122960,-10.974487,-0.734146,-7.829734,-6.770842,-13.666861
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Index 95,-4.112835,7.385291,-13.851625,-6.078196,11.023885,-5.512976,1.231175,6.411213,-1.683794,4.646666,18.364089,6.956441
96,Index 96,-4.436619,2.669846,6.218075,-9.575880,-3.399697,14.107305,-8.542899,7.253396,-0.474596,-11.268330,19.082276,1.434360
97,Index 97,-2.641866,-0.605210,-1.159309,10.960797,-20.105969,10.573056,3.127534,2.846807,7.143668,5.478037,0.536783,2.569418
98,Index 98,13.237843,-13.885348,18.912088,3.159741,-8.686046,-5.722742,4.098118,3.469731,-7.391454,7.783543,-8.647712,-10.910139
99,Index 99,16.327530,9.128792,11.217098,8.639888,0.715028,-1.312129,-1.885473,10.439447,0.101048,-0.820258,-3.173715,5.438891

### Aus einer Excel Datei

In [22]:
df_excel2 = pd.read_excel(
    excel_file2,
    index_col=0,
    
    header=0,
    skiprows=[1]
)

In [26]:
df_excel2

                    -11.236758   2.218171
-9.071786174248082
-0.974754            -7.153281    2.798292
 10.134367           -4.369057  -15.880210
 12.319482            2.746217    6.987371
 3.138766            -2.165214    2.617773
-24.955057          -10.417922  -17.464209
-13.253936           11.754344   -4.116406


### Andere Formate:

- `pd.read_clipboard`
- `pd.read_html`
- `pd.read_json`
- `pd.read_pickle`
- `pd.read_sql` (verwendet SQLAlchemy um auf die Datenbank zuzugreifen)
- ...


## Mini-Workshop: Erzeugen von Data Frames

In der Datei `boston-housing.csv` (im Verzeichnis `data/pandas`) ist eine Tabelle
mit Immobilienpreisen in Boston gespeichert. Laden Sie diese Tabelle in einen
Pandas DataFrame.

In [28]:
df_california = pd.read_csv(pandas_dir_path / "california-housing.csv")

In [31]:
df_california

,Unnamed: 0,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
0,0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...,...
20635,20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894


Die Excel-Datei `housing-data.xlsx` (im Verzeichnis `data/pandas`) enthält zwei
Sheets: `Boston` und `California`. Laden Sie diese Tabellen in Pandas Data Frames.